// This file is auto-generated by Payload CMS during build.
// Do not edit manually — it will be overwritten.
// Run `npm run build` to regenerate.
import type { ImportMap } from 'payload'

export const importMap: ImportMap = {}
