/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    projects: Project;
    certificates: Certificate;
    articles: Article;
    'contact-submissions': ContactSubmission;
    clients: Client;
    pages: Page;
    team: Team;
    'crew-gallery': CrewGallery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'crew-gallery': CrewGallerySelect<false> | CrewGallerySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    stats: Stat;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * مثال: industrial-piping — فقط حروف انگلیسی، اعداد و خط تیره
   */
  slug: string;
  shortDescription: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  ctaText?: string | null;
  /**
   * عدد کمتر = نمایش اول
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  location?: string | null;
  client?: string | null;
  serviceDescription: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedServices?: (number | Service)[] | null;
  relatedService?: (number | null) | Service;
  coverImage?: (number | null) | Media;
  beforeAfterImages?:
    | {
        before?: (number | null) | Media;
        after?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * تصویر اسکن شده تاییدیه حسن انجام کار صادر شده توسط کارفرمای پروژه
   */
  satisfactionLetter?: (number | null) | Media;
  satisfactionNotes?: string | null;
  completionDate?: string | null;
  status: 'in-progress' | 'completed';
  /**
   * این پروژه در بخش پروژه‌های شاخص صفحه اصلی نمایش داده می‌شود
   */
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  name: string;
  type: 'iso-9001' | 'iso-14001' | 'iso-45001' | 'hse' | 'welding' | 'inspection' | 'other';
  issuer?: string | null;
  certificateNumber?: string | null;
  issueDate?: string | null;
  expiryDate?: string | null;
  image?: (number | null) | Media;
  description?: string | null;
  featured?: boolean | null;
  /**
   * عدد کوچک‌تر در ابتدا نمایش داده می‌شود (مثلاً ۱، ۲، ۳...)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * مثال: asme-b31-3-piping-standards — حروف انگلیسی و خط تیره
   */
  slug: string;
  summary: string;
  author?: string | null;
  readingTime?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  category?: ('technical' | 'company' | 'projects' | 'certificates' | 'industry') | null;
  publishDate: string;
  published?: boolean | null;
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  requestType: 'piping' | 'mechanical' | 'welding' | 'structure' | 'overhaul' | 'sandblast' | 'manpower' | 'other';
  notes?: string | null;
  status?: ('new' | 'reviewing' | 'responded' | 'closed') | null;
  /**
   * این یادداشت فقط برای ادمین قابل مشاهده است
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  website?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroBadge?: string | null;
  heroImage?: (number | null) | Media;
  storyTitle?: string | null;
  bodyContent?: string | null;
  /**
   * فایل ویدیوی اختصاصی تیزر یا معرفی برای این صفحه
   */
  video?: (number | null) | Media;
  /**
   * در صورت عدم آپلود فایل در رسانه، می‌توانید لینک مستقیم MP4 را وارد کنید
   */
  videoUrl?: string | null;
  videoCover?: (number | null) | Media;
  teamSectionBadge?: string | null;
  teamSectionTitle?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * مثال: مدیرعامل و رئیس هیئت مدیره / مدیر پروژه‌ها / سرپرست کارگاه
   */
  role: string;
  /**
   * در صورت فعال بودن، در بخش ویژه پیام مدیرعامل نمایش داده می‌شود
   */
  isCeo?: boolean | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  /**
   * نقل قول یا پیام اصلی مدیرعامل خطاب به کارفرمایان
   */
  quote?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * عدد کمتر = نمایش اول
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crew-gallery".
 */
export interface CrewGallery {
  id: number;
  title: string;
  category: 'welders' | 'fitters' | 'piping' | 'mechanical' | 'tanks' | 'sandblast' | 'civil' | 'hse' | 'team';
  /**
   * اگر دسته‌بندی جدیدی مد نظر دارید می‌توانید در این بخش وارد نمایید.
   */
  customCategory?: string | null;
  image?: (number | null) | Media;
  caption?: string | null;
  location?: string | null;
  relatedService?: (number | null) | Service;
  relatedProject?: (number | null) | Project;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'crew-gallery';
        value: number | CrewGallery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  icon?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  ctaText?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  location?: T;
  client?: T;
  serviceDescription?: T;
  description?: T;
  relatedServices?: T;
  relatedService?: T;
  coverImage?: T;
  beforeAfterImages?:
    | T
    | {
        before?: T;
        after?: T;
        caption?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  satisfactionLetter?: T;
  satisfactionNotes?: T;
  completionDate?: T;
  status?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  issuer?: T;
  certificateNumber?: T;
  issueDate?: T;
  expiryDate?: T;
  image?: T;
  description?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  author?: T;
  readingTime?: T;
  content?: T;
  coverImage?: T;
  category?: T;
  publishDate?: T;
  published?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  requestType?: T;
  notes?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroBadge?: T;
  heroImage?: T;
  storyTitle?: T;
  bodyContent?: T;
  video?: T;
  videoUrl?: T;
  videoCover?: T;
  teamSectionBadge?: T;
  teamSectionTitle?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  isCeo?: T;
  photo?: T;
  bio?: T;
  quote?: T;
  email?: T;
  phone?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crew-gallery_select".
 */
export interface CrewGallerySelect<T extends boolean = true> {
  title?: T;
  category?: T;
  customCategory?: T;
  image?: T;
  caption?: T;
  location?: T;
  relatedService?: T;
  relatedProject?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  navItems?:
    | {
        label: string;
        /**
         * مثال: / ، /about ، /services ، /projects ، /articles ، /contact
         */
        href: string;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  titleFont?: ('YekanBakh' | 'IRANSansX' | 'Vazirmatn' | 'Anjoman' | 'Kamand') | null;
  textFont?: ('IRANSansX' | 'YekanBakh' | 'Vazirmatn') | null;
  /**
   * کد Hex رنگ عناوین (مانند #111827 مشکی، #1A365D سرمه‌ای، #F97316 نارنجی)
   */
  titleColor?: string | null;
  /**
   * کد Hex رنگ زیرعنوان‌ها (مانند #4b5563 خاکستری)
   */
  subtitleColor?: string | null;
  /**
   * کد Hex رنگ متن اصلی (مانند #111827)
   */
  textColor?: string | null;
  heroType: 'video' | 'slider' | 'presentation';
  /**
   * فایل ویدیو (MP4 توصیه می‌شود)
   */
  heroVideo?: (number | null) | Media;
  /**
   * فایل یا ویدیو اصلی تیزر معرفی شرکت برای حالت Presentation
   */
  presentationVideo?: (number | null) | Media;
  /**
   * در صورت عدم آپلود فایل رسانه، می‌توانید لینک مستقیم ویدیو MP4 را اینجا وارد کنید
   */
  presentationVideoUrl?: string | null;
  presentationVideoCover?: (number | null) | Media;
  /**
   * تصویر پس‌زمینه حالت ویدیو معرفی سه‌بعدی (در صورت عدم آپلود از تصویر پیش‌فرض بوکه صنعتی استفاده می‌شود)
   */
  presentationBgImage?: (number | null) | Media;
  presentationBadge?: string | null;
  presentationTitle?: string | null;
  presentationSubtitle?: string | null;
  presentationPrimaryBtnText?: string | null;
  presentationPrimaryBtnLink?: string | null;
  presentationSecondaryBtnText?: string | null;
  presentationSecondaryBtnLink?: string | null;
  heroSlides?:
    | {
        image?: (number | null) | Media;
        title?: string | null;
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroTagline?: string | null;
  phone1?: string | null;
  phone2?: string | null;
  mobile?: string | null;
  email?: string | null;
  email2?: string | null;
  workingHours?: string | null;
  postalCode?: string | null;
  address?: string | null;
  mapEmbedUrl?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  footerDescription?: string | null;
  footerCopyrightText?: string | null;
  footerDevCredit?: string | null;
  footerQuickLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * آمارهای نمایش داده شده در صفحه اصلی
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  foundedYear: number;
  projectsCompleted: number;
  specialists: number;
  trustedClients: number;
  /**
   * مثال: ۱۵۰+
   */
  showPlusSign?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        order?: T;
        id?: T;
      };
  titleFont?: T;
  textFont?: T;
  titleColor?: T;
  subtitleColor?: T;
  textColor?: T;
  heroType?: T;
  heroVideo?: T;
  presentationVideo?: T;
  presentationVideoUrl?: T;
  presentationVideoCover?: T;
  presentationBgImage?: T;
  presentationBadge?: T;
  presentationTitle?: T;
  presentationSubtitle?: T;
  presentationPrimaryBtnText?: T;
  presentationPrimaryBtnLink?: T;
  presentationSecondaryBtnText?: T;
  presentationSecondaryBtnLink?: T;
  heroSlides?:
    | T
    | {
        image?: T;
        title?: T;
        subtitle?: T;
        id?: T;
      };
  heroTitle?: T;
  heroSubtitle?: T;
  heroTagline?: T;
  phone1?: T;
  phone2?: T;
  mobile?: T;
  email?: T;
  email2?: T;
  workingHours?: T;
  postalCode?: T;
  address?: T;
  mapEmbedUrl?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  footerDescription?: T;
  footerCopyrightText?: T;
  footerDevCredit?: T;
  footerQuickLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  foundedYear?: T;
  projectsCompleted?: T;
  specialists?: T;
  trustedClients?: T;
  showPlusSign?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}