/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_projects_status = pgEnum("enum_projects_status", [
  "in-progress",
  "completed",
]);
export const enum_certificates_type = pgEnum("enum_certificates_type", [
  "iso-9001",
  "iso-14001",
  "iso-45001",
  "hse",
  "welding",
  "inspection",
  "other",
]);
export const enum_articles_category = pgEnum("enum_articles_category", [
  "technical",
  "company",
  "projects",
  "certificates",
  "industry",
]);
export const enum_contact_submissions_request_type = pgEnum(
  "enum_contact_submissions_request_type",
  [
    "piping",
    "mechanical",
    "welding",
    "structure",
    "overhaul",
    "sandblast",
    "manpower",
    "other",
  ],
);
export const enum_contact_submissions_status = pgEnum(
  "enum_contact_submissions_status",
  ["new", "reviewing", "responded", "closed"],
);
export const enum_site_settings_title_font = pgEnum(
  "enum_site_settings_title_font",
  ["YekanBakh", "IRANSansX", "Vazirmatn", "Anjoman", "Kamand"],
);
export const enum_site_settings_text_font = pgEnum(
  "enum_site_settings_text_font",
  ["IRANSansX", "YekanBakh", "Vazirmatn"],
);
export const enum_site_settings_hero_type = pgEnum(
  "enum_site_settings_hero_type",
  ["video", "slider"],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt"),
    caption: varchar("caption"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_hero_sizes_hero_filename_idx").on(
      columns.sizes_hero_filename,
    ),
  ],
);

export const services_gallery = pgTable(
  "services_gallery",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    caption: varchar("caption"),
  },
  (columns) => [
    index("services_gallery_order_idx").on(columns._order),
    index("services_gallery_parent_id_idx").on(columns._parentID),
    index("services_gallery_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [services.id],
      name: "services_gallery_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const services_features = pgTable(
  "services_features",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    feature: varchar("feature").notNull(),
  },
  (columns) => [
    index("services_features_order_idx").on(columns._order),
    index("services_features_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [services.id],
      name: "services_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const services_faqs = pgTable(
  "services_faqs",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    question: varchar("question").notNull(),
    answer: varchar("answer").notNull(),
  },
  (columns) => [
    index("services_faqs_order_idx").on(columns._order),
    index("services_faqs_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [services.id],
      name: "services_faqs_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const services = pgTable(
  "services",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    shortDescription: varchar("short_description").notNull(),
    description: jsonb("description"),
    icon: integer("icon_id").references(() => media.id, {
      onDelete: "set null",
    }),
    coverImage: integer("cover_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    ctaText: varchar("cta_text").default("استعلام و مشاوره تخصصی"),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("services_slug_idx").on(columns.slug),
    index("services_icon_idx").on(columns.icon),
    index("services_cover_image_idx").on(columns.coverImage),
    index("services_updated_at_idx").on(columns.updatedAt),
    index("services_created_at_idx").on(columns.createdAt),
  ],
);

export const projects_before_after_images = pgTable(
  "projects_before_after_images",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    before: integer("before_id").references(() => media.id, {
      onDelete: "set null",
    }),
    after: integer("after_id").references(() => media.id, {
      onDelete: "set null",
    }),
    caption: varchar("caption"),
  },
  (columns) => [
    index("projects_before_after_images_order_idx").on(columns._order),
    index("projects_before_after_images_parent_id_idx").on(columns._parentID),
    index("projects_before_after_images_before_idx").on(columns.before),
    index("projects_before_after_images_after_idx").on(columns.after),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [projects.id],
      name: "projects_before_after_images_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const projects_gallery = pgTable(
  "projects_gallery",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    caption: varchar("caption"),
  },
  (columns) => [
    index("projects_gallery_order_idx").on(columns._order),
    index("projects_gallery_parent_id_idx").on(columns._parentID),
    index("projects_gallery_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [projects.id],
      name: "projects_gallery_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const projects = pgTable(
  "projects",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    location: varchar("location"),
    client: varchar("client"),
    serviceDescription: varchar("service_description").notNull(),
    description: jsonb("description"),
    relatedService: integer("related_service_id").references(
      () => services.id,
      {
        onDelete: "set null",
      },
    ),
    coverImage: integer("cover_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    satisfactionLetter: integer("satisfaction_letter_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    satisfactionNotes: varchar("satisfaction_notes"),
    completionDate: timestamp("completion_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    status: enum_projects_status("status").notNull().default("completed"),
    featured: boolean("featured").default(false),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("projects_slug_idx").on(columns.slug),
    index("projects_related_service_idx").on(columns.relatedService),
    index("projects_cover_image_idx").on(columns.coverImage),
    index("projects_satisfaction_letter_idx").on(columns.satisfactionLetter),
    index("projects_updated_at_idx").on(columns.updatedAt),
    index("projects_created_at_idx").on(columns.createdAt),
  ],
);

export const certificates = pgTable(
  "certificates",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    type: enum_certificates_type("type").notNull(),
    issuer: varchar("issuer"),
    certificateNumber: varchar("certificate_number"),
    issueDate: timestamp("issue_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiryDate: timestamp("expiry_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    description: varchar("description"),
    featured: boolean("featured").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("certificates_image_idx").on(columns.image),
    index("certificates_updated_at_idx").on(columns.updatedAt),
    index("certificates_created_at_idx").on(columns.createdAt),
  ],
);

export const articles = pgTable(
  "articles",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    summary: varchar("summary").notNull(),
    author: varchar("author").default("تیم فنی ضرغام صنعت اروند"),
    readingTime: varchar("reading_time").default("۵ دقیقه"),
    content: jsonb("content").notNull(),
    coverImage: integer("cover_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    category: enum_articles_category("category").default("technical"),
    publishDate: timestamp("publish_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    published: boolean("published").default(true),
    featured: boolean("featured").default(false),
    seo_metaTitle: varchar("seo_meta_title"),
    seo_metaDescription: varchar("seo_meta_description"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("articles_slug_idx").on(columns.slug),
    index("articles_cover_image_idx").on(columns.coverImage),
    index("articles_updated_at_idx").on(columns.updatedAt),
    index("articles_created_at_idx").on(columns.createdAt),
  ],
);

export const contact_submissions = pgTable(
  "contact_submissions",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    phone: varchar("phone").notNull(),
    email: varchar("email"),
    requestType:
      enum_contact_submissions_request_type("request_type").notNull(),
    notes: varchar("notes"),
    status: enum_contact_submissions_status("status").default("new"),
    adminNotes: varchar("admin_notes"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("contact_submissions_updated_at_idx").on(columns.updatedAt),
    index("contact_submissions_created_at_idx").on(columns.createdAt),
  ],
);

export const clients = pgTable(
  "clients",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    website: varchar("website"),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("clients_logo_idx").on(columns.logo),
    index("clients_updated_at_idx").on(columns.updatedAt),
    index("clients_created_at_idx").on(columns.createdAt),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    heroTitle: varchar("hero_title"),
    heroSubtitle: varchar("hero_subtitle"),
    heroBadge: varchar("hero_badge"),
    heroImage: integer("hero_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    storyTitle: varchar("story_title"),
    bodyContent: varchar("body_content"),
    metaTitle: varchar("meta_title"),
    metaDescription: varchar("meta_description"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("pages_slug_idx").on(columns.slug),
    index("pages_hero_image_idx").on(columns.heroImage),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
  ],
);

export const team = pgTable(
  "team",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    role: varchar("role").notNull(),
    isCeo: boolean("is_ceo").default(false),
    photo: integer("photo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    bio: varchar("bio"),
    quote: varchar("quote"),
    email: varchar("email"),
    phone: varchar("phone"),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("team_photo_idx").on(columns.photo),
    index("team_updated_at_idx").on(columns.updatedAt),
    index("team_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    servicesID: integer("services_id"),
    projectsID: integer("projects_id"),
    certificatesID: integer("certificates_id"),
    articlesID: integer("articles_id"),
    "contact-submissionsID": integer("contact_submissions_id"),
    clientsID: integer("clients_id"),
    pagesID: integer("pages_id"),
    teamID: integer("team_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_services_id_idx").on(
      columns.servicesID,
    ),
    index("payload_locked_documents_rels_projects_id_idx").on(
      columns.projectsID,
    ),
    index("payload_locked_documents_rels_certificates_id_idx").on(
      columns.certificatesID,
    ),
    index("payload_locked_documents_rels_articles_id_idx").on(
      columns.articlesID,
    ),
    index("payload_locked_documents_rels_contact_submissions_id_idx").on(
      columns["contact-submissionsID"],
    ),
    index("payload_locked_documents_rels_clients_id_idx").on(columns.clientsID),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_team_id_idx").on(columns.teamID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["servicesID"]],
      foreignColumns: [services.id],
      name: "payload_locked_documents_rels_services_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["projectsID"]],
      foreignColumns: [projects.id],
      name: "payload_locked_documents_rels_projects_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["certificatesID"]],
      foreignColumns: [certificates.id],
      name: "payload_locked_documents_rels_certificates_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["articlesID"]],
      foreignColumns: [articles.id],
      name: "payload_locked_documents_rels_articles_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["contact-submissionsID"]],
      foreignColumns: [contact_submissions.id],
      name: "payload_locked_documents_rels_contact_submissions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["clientsID"]],
      foreignColumns: [clients.id],
      name: "payload_locked_documents_rels_clients_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["teamID"]],
      foreignColumns: [team.id],
      name: "payload_locked_documents_rels_team_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings_nav_items = pgTable(
  "site_settings_nav_items",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    href: varchar("href").notNull(),
    order: numeric("order", { mode: "number" }).default(0),
  },
  (columns) => [
    index("site_settings_nav_items_order_idx").on(columns._order),
    index("site_settings_nav_items_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_nav_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_hero_slides = pgTable(
  "site_settings_hero_slides",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    title: varchar("title"),
    subtitle: varchar("subtitle"),
  },
  (columns) => [
    index("site_settings_hero_slides_order_idx").on(columns._order),
    index("site_settings_hero_slides_parent_id_idx").on(columns._parentID),
    index("site_settings_hero_slides_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_hero_slides_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings = pgTable(
  "site_settings",
  {
    id: serial("id").primaryKey(),
    companyName: varchar("company_name").notNull().default("ضرغام صنعت اروند"),
    tagline: varchar("tagline").default("پیمانکاری، صنعتی، پایپینگ و مکانیکال"),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    favicon: integer("favicon_id").references(() => media.id, {
      onDelete: "set null",
    }),
    titleFont: enum_site_settings_title_font("title_font").default("YekanBakh"),
    textFont: enum_site_settings_text_font("text_font").default("IRANSansX"),
    titleColor: varchar("title_color").default("#111827"),
    subtitleColor: varchar("subtitle_color").default("#4b5563"),
    textColor: varchar("text_color").default("#111827"),
    heroType: enum_site_settings_hero_type("hero_type")
      .notNull()
      .default("slider"),
    heroVideo: integer("hero_video_id").references(() => media.id, {
      onDelete: "set null",
    }),
    heroTitle: varchar("hero_title").default(
      "مجری پروژه‌های نفت، گاز، پتروشیمی و صنایع مختلف",
    ),
    heroSubtitle: varchar("hero_subtitle").default(
      "اجرای عملیات پایپینگ، نصب تجهیزات مکانیکی، سیویل و ساخت مخازن با بالاترین استانداردهای کیفی",
    ),
    heroTagline: varchar("hero_tagline").default(
      "کیفیت، ایمنی، تعهد: پایه‌های اعتماد",
    ),
    phone1: varchar("phone1").default("061-53328646"),
    phone2: varchar("phone2").default("0916-000-0000"),
    mobile: varchar("mobile").default("0916-000-0000"),
    email: varchar("email").default("info@zarghamsanat.com"),
    email2: varchar("email2").default("zarghamsanat@gmail.com"),
    workingHours: varchar("working_hours").default(
      "شنبه تا چهارشنبه: ۸ الی ۱۷ | پنجشنبه: ۸ الی ۱۳",
    ),
    postalCode: varchar("postal_code").default("6317814564"),
    address: varchar("address").default(
      "آبادان، کوی قدس، خیابان بهار ۲۷، پلاک ۵",
    ),
    mapEmbedUrl: varchar("map_embed_url"),
    metaTitle: varchar("meta_title").default(
      "ضرغام صنعت اروند | پایپینگ صنعتی، تجهیزات مکانیکی و پروژه‌های نفت و گاز",
    ),
    metaDescription: varchar("meta_description").default(
      "شرکت ضرغام صنعت اروند مجری پروژه‌های نفت، گاز، پتروشیمی، پایپینگ صنعتی، نصب تجهیزات مکانیکی، سیویل و ساخت مخازن ذخیره با بیش از یک دهه تجربه در سطح کشور.",
    ),
    ogImage: integer("og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("site_settings_logo_idx").on(columns.logo),
    index("site_settings_favicon_idx").on(columns.favicon),
    index("site_settings_hero_video_idx").on(columns.heroVideo),
    index("site_settings_og_image_idx").on(columns.ogImage),
  ],
);

export const stats = pgTable("stats", {
  id: serial("id").primaryKey(),
  foundedYear: numeric("founded_year", { mode: "number" })
    .notNull()
    .default(1390),
  projectsCompleted: numeric("projects_completed", { mode: "number" })
    .notNull()
    .default(150),
  specialists: numeric("specialists", { mode: "number" }).notNull().default(80),
  trustedClients: numeric("trusted_clients", { mode: "number" })
    .notNull()
    .default(40),
  showPlusSign: boolean("show_plus_sign").default(true),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_services_gallery = relations(
  services_gallery,
  ({ one }) => ({
    _parentID: one(services, {
      fields: [services_gallery._parentID],
      references: [services.id],
      relationName: "gallery",
    }),
    image: one(media, {
      fields: [services_gallery.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_services_features = relations(
  services_features,
  ({ one }) => ({
    _parentID: one(services, {
      fields: [services_features._parentID],
      references: [services.id],
      relationName: "features",
    }),
  }),
);
export const relations_services_faqs = relations(services_faqs, ({ one }) => ({
  _parentID: one(services, {
    fields: [services_faqs._parentID],
    references: [services.id],
    relationName: "faqs",
  }),
}));
export const relations_services = relations(services, ({ one, many }) => ({
  icon: one(media, {
    fields: [services.icon],
    references: [media.id],
    relationName: "icon",
  }),
  coverImage: one(media, {
    fields: [services.coverImage],
    references: [media.id],
    relationName: "coverImage",
  }),
  gallery: many(services_gallery, {
    relationName: "gallery",
  }),
  features: many(services_features, {
    relationName: "features",
  }),
  faqs: many(services_faqs, {
    relationName: "faqs",
  }),
}));
export const relations_projects_before_after_images = relations(
  projects_before_after_images,
  ({ one }) => ({
    _parentID: one(projects, {
      fields: [projects_before_after_images._parentID],
      references: [projects.id],
      relationName: "beforeAfterImages",
    }),
    before: one(media, {
      fields: [projects_before_after_images.before],
      references: [media.id],
      relationName: "before",
    }),
    after: one(media, {
      fields: [projects_before_after_images.after],
      references: [media.id],
      relationName: "after",
    }),
  }),
);
export const relations_projects_gallery = relations(
  projects_gallery,
  ({ one }) => ({
    _parentID: one(projects, {
      fields: [projects_gallery._parentID],
      references: [projects.id],
      relationName: "gallery",
    }),
    image: one(media, {
      fields: [projects_gallery.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_projects = relations(projects, ({ one, many }) => ({
  relatedService: one(services, {
    fields: [projects.relatedService],
    references: [services.id],
    relationName: "relatedService",
  }),
  coverImage: one(media, {
    fields: [projects.coverImage],
    references: [media.id],
    relationName: "coverImage",
  }),
  beforeAfterImages: many(projects_before_after_images, {
    relationName: "beforeAfterImages",
  }),
  gallery: many(projects_gallery, {
    relationName: "gallery",
  }),
  satisfactionLetter: one(media, {
    fields: [projects.satisfactionLetter],
    references: [media.id],
    relationName: "satisfactionLetter",
  }),
}));
export const relations_certificates = relations(certificates, ({ one }) => ({
  image: one(media, {
    fields: [certificates.image],
    references: [media.id],
    relationName: "image",
  }),
}));
export const relations_articles = relations(articles, ({ one }) => ({
  coverImage: one(media, {
    fields: [articles.coverImage],
    references: [media.id],
    relationName: "coverImage",
  }),
}));
export const relations_contact_submissions = relations(
  contact_submissions,
  () => ({}),
);
export const relations_clients = relations(clients, ({ one }) => ({
  logo: one(media, {
    fields: [clients.logo],
    references: [media.id],
    relationName: "logo",
  }),
}));
export const relations_pages = relations(pages, ({ one }) => ({
  heroImage: one(media, {
    fields: [pages.heroImage],
    references: [media.id],
    relationName: "heroImage",
  }),
}));
export const relations_team = relations(team, ({ one }) => ({
  photo: one(media, {
    fields: [team.photo],
    references: [media.id],
    relationName: "photo",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    servicesID: one(services, {
      fields: [payload_locked_documents_rels.servicesID],
      references: [services.id],
      relationName: "services",
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: "projects",
    }),
    certificatesID: one(certificates, {
      fields: [payload_locked_documents_rels.certificatesID],
      references: [certificates.id],
      relationName: "certificates",
    }),
    articlesID: one(articles, {
      fields: [payload_locked_documents_rels.articlesID],
      references: [articles.id],
      relationName: "articles",
    }),
    "contact-submissionsID": one(contact_submissions, {
      fields: [payload_locked_documents_rels["contact-submissionsID"]],
      references: [contact_submissions.id],
      relationName: "contact-submissions",
    }),
    clientsID: one(clients, {
      fields: [payload_locked_documents_rels.clientsID],
      references: [clients.id],
      relationName: "clients",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    teamID: one(team, {
      fields: [payload_locked_documents_rels.teamID],
      references: [team.id],
      relationName: "team",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_site_settings_nav_items = relations(
  site_settings_nav_items,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_nav_items._parentID],
      references: [site_settings.id],
      relationName: "navItems",
    }),
  }),
);
export const relations_site_settings_hero_slides = relations(
  site_settings_hero_slides,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_hero_slides._parentID],
      references: [site_settings.id],
      relationName: "heroSlides",
    }),
    image: one(media, {
      fields: [site_settings_hero_slides.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_site_settings = relations(
  site_settings,
  ({ one, many }) => ({
    logo: one(media, {
      fields: [site_settings.logo],
      references: [media.id],
      relationName: "logo",
    }),
    favicon: one(media, {
      fields: [site_settings.favicon],
      references: [media.id],
      relationName: "favicon",
    }),
    navItems: many(site_settings_nav_items, {
      relationName: "navItems",
    }),
    heroVideo: one(media, {
      fields: [site_settings.heroVideo],
      references: [media.id],
      relationName: "heroVideo",
    }),
    heroSlides: many(site_settings_hero_slides, {
      relationName: "heroSlides",
    }),
    ogImage: one(media, {
      fields: [site_settings.ogImage],
      references: [media.id],
      relationName: "ogImage",
    }),
  }),
);
export const relations_stats = relations(stats, () => ({}));

type DatabaseSchema = {
  enum_projects_status: typeof enum_projects_status;
  enum_certificates_type: typeof enum_certificates_type;
  enum_articles_category: typeof enum_articles_category;
  enum_contact_submissions_request_type: typeof enum_contact_submissions_request_type;
  enum_contact_submissions_status: typeof enum_contact_submissions_status;
  enum_site_settings_title_font: typeof enum_site_settings_title_font;
  enum_site_settings_text_font: typeof enum_site_settings_text_font;
  enum_site_settings_hero_type: typeof enum_site_settings_hero_type;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  services_gallery: typeof services_gallery;
  services_features: typeof services_features;
  services_faqs: typeof services_faqs;
  services: typeof services;
  projects_before_after_images: typeof projects_before_after_images;
  projects_gallery: typeof projects_gallery;
  projects: typeof projects;
  certificates: typeof certificates;
  articles: typeof articles;
  contact_submissions: typeof contact_submissions;
  clients: typeof clients;
  pages: typeof pages;
  team: typeof team;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_settings_nav_items: typeof site_settings_nav_items;
  site_settings_hero_slides: typeof site_settings_hero_slides;
  site_settings: typeof site_settings;
  stats: typeof stats;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_services_gallery: typeof relations_services_gallery;
  relations_services_features: typeof relations_services_features;
  relations_services_faqs: typeof relations_services_faqs;
  relations_services: typeof relations_services;
  relations_projects_before_after_images: typeof relations_projects_before_after_images;
  relations_projects_gallery: typeof relations_projects_gallery;
  relations_projects: typeof relations_projects;
  relations_certificates: typeof relations_certificates;
  relations_articles: typeof relations_articles;
  relations_contact_submissions: typeof relations_contact_submissions;
  relations_clients: typeof relations_clients;
  relations_pages: typeof relations_pages;
  relations_team: typeof relations_team;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_settings_nav_items: typeof relations_site_settings_nav_items;
  relations_site_settings_hero_slides: typeof relations_site_settings_hero_slides;
  relations_site_settings: typeof relations_site_settings;
  relations_stats: typeof relations_stats;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
